### ISSUE TITLE
New Cases

### ISSUE THREAD

**Issue by JordanBienvenue** [heremaps/here-covid-19-tracker#4]
Add Mauritius Island .. 3 Cases confirmed

**Comment by tangellapelly** [comment]
Hi JordanBienvenue, thanks for notifying us. The map data is sync every 24 hours based on the JHU repo [CSSEGISandData/COVID-19](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series)
